airflowVersion: 2.11.2
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.11.2-python3.11"

postgresql:
  enabled: false

airflow:
  config:
    core:
      load_examples: "False"
      executor: "SequentialExecutor"
    database:
      sql_alchemy_conn: postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow
    webserver:
      secret_key: ""
    logging:
      remote_logging: "False"

service:
  type: ClusterIP

redis:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

webserver:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

dagsProcessor:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

triggerer:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi

statsd:
  enabled: true

createUserJob:
  enabled: true
  defaultUser:
    role: Admin
    username: airflow
    email: airflow@airflow.com
    firstName: airflow
    lastName: user
    password: airflow

dags:
  gitSync:
    enabled: true
    repo: https://github.com/Nebula-London/MLOps-devopscube.git
    branch: main
    subPath: dags
    depth: 1

runMigrations:
  enabled: true
