airflowVersion: 2.11.2
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.11.2-python3.11"

postgresql:
  enabled: false

executor: "KubernetesExecutor"

service:
  type: ClusterIP

webserver:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

triggerer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi

statsd:
  enabled: true

createUserJob:
  enabled: true
  defaultUser:
    role: Admin
    username: airflow
    email: airflow@airflow.com
    firstName: airflow
    lastName: user
    password: airflow

dags:
  gitSync:
    enabled: true
    repo: https://github.com/Nebula-London/MLOps-devopscube.git
    branch: main
    subPath: dags
    depth: 1

runMigrations:
  enabled: true
